plugins {
    id "java"
}

allprojects {
    group = "com.mparkersierra.ftcsim"
    version = "1.0.0"
}

subprojects {
    plugins.withType(JavaPlugin).configureEach {
        java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(17)
            }
        }
    }
}
